package ru.oogis.hydra.util;

public enum MessageKey
{
	ERR_CONFIG_SAVE, ERR_ILLEGAL_CHANNEL_TEMPLATE, ERR_RESTART_CHANNEL,
	ERR_START_CHANNEL, ERR_STOP_CHANNEL, ERR_UNKNOWN_CSV_DATASET_ID,
	LBL_ROUTE_SD_TO_DESC, LBL_ROUTE_SD_TO_NAME, LBL_ROUTE_SD_TO_UOM,
	MSG_CHANNEL_ADDED, MSG_CHANNEL_REMOVED, MSG_CHANNEL_RESTART,
	MSG_CHANNEL_STARTED, MSG_CHANNEL_STOPPED, MSG_CONFIG_LOADED,
	MSG_CONFIG_UNLOADED, WARN_MSG_TIMEOUT, WARN_JNDI_UNBIND
}
